### ISSUE TITLE
operation not allowed by the security policy `PS' @ 

### ISSUE THREAD

**Issue by optio50** [NoahCristino/easywifi#1]
Xubuntu 19.1
I have installed in these locations
/usr/bin/nmcli
/usr/bin/python1
/usr/bin/python2
/usr/bin/python3
Tried with and without sudo.

import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
from: can't read /var/mail/shlex
from: can't read /var/mail/getpass
from: can't read /var/mail/shutil
from: can't read /var/mail/sys
./easywifi.py: 6: class: not found
./easywifi.py: 7: HEADER: not found
./easywifi.py: 8: OKBLUE: not found
./easywifi.py: 9: OKGREEN: not found
./easywifi.py: 10: WARNING: not found
./easywifi.py: 11: FAIL: not found
./easywifi.py: 12: ENDC: not found
./easywifi.py: 13: BOLD: not found
./easywifi.py: 14: UNDERLINE: not found
./easywifi.py: 15: Syntax error: word unexpected (expecting ")")

**Comment by optio50** [comment]
Never mind I didnt notice you didnt set the environment

#!/usr/bin/env python3

**Comment by OKWEnick** [comment]
hello, am using ubuntu 20.04, what if I copy the above code and paste it into my terminal, will it still create a python environment in order to import pybrake?      (#!/usr/bin/env python3)

**Comment by colesnicov** [comment]
> hello, am using ubuntu 20.04, what if I copy the above code and paste it into my terminal, will it still create a python environment in order to import pybrake? (#!/usr/bin/env python3)

```$ python3  ./runva_vosk.py```
